// This file is auto-generated by react-native-prebuilt-lucide-icons
// Please do not edit this file manually.
// You can find the icons at https://lucide.dev/

import type { FC, SVGProps } from "react";
import { type LucideProps } from "lucide-react";

export type Icon = FC<Omit<LucideProps, "ref">>;

export declare const Capture: Icon;
